languageCode = 'en-us'
title = "Life of Prakhar"
theme = 'paper'

baseURL = '/'
relativeURLs = true
uglyURLs = true
publishDir = 'lifeBlog'



disqusShortname = 'prakharLife'   # use disqus comments

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'prakhartiwari0'               # twitter.com/YOUR_TWITTER_ID
  github = 'prakhartiwari0'                 # github.com/YOUR_GITHUB_ID
  instagram = 'prakhartiwari0'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'prakhartiwari0'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'https://mastodon.social/@prakhartiwari0'           # e.g. 'https://mastodon.instance/@xxx'
  rss = false                     # show rss icon

  # home page profile
  avatar = 'https://github.com/prakhartiwari0.png' # gravatar email or image url
  name = 'Prakhar Tiwari'
  bio = 'Student Developer'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally